    <div class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark">   
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <div class="navbar-nav">
                            <a class="nav-link active" aria-current="page" href="/">Анализатор страниц</a>
                            <a class="nav-link" href="/">Главная</a>
                            <a class="nav-link" href="/urls">Сайты</a>
                        </div>
                    </div>
            </nav> 
        </div> 
    </div>