<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Анализатор страниц</title>
</head>
<body>
    <?php require '_header.phtml' ?>


    <div class="container mt-3">
        <div class="row">

           

            <div class=" col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                <form action="/urls" method="post" class="row" required="">
                    <div class="col-8">
                         <label for="text" class="visually-hidden">Url для проверки</label>
                         <input type="text" name="url[name]" value="" class="form-control form-control-lg <?= $inputValid ? '' : 'is-invalid'?>" placeholder="https://www.example.com">
                         <?= $inputValid ? '': '<div class=invalid-feedback>Некорректный URL</div>'?>
                    </div>
                    <div class="col-2">
                         <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
                    </div>
                </form>

            </div>

   
        </div>
    </div>
         
  










    </body>
</html>