<!DOCTYPE html>
<html lang="en">
<?php require '_head.phtml' ?>

<body class="min-vh-100 d-flex flex-column">
    <?php require '_header.phtml' ?>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <div class="row">
                <div class=" col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                    <h1 class="display-3">Анализатор страниц</h1>
                    <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                    <form action="/urls" method="post" class="row" required="">
                        <div class="col-8">
                            <label for="text" class="visually-hidden">Url для проверки</label>
                            <input type="text" name="url[name]" value="" class="form-control form-control-lg <?= $inputValid ? '' : 'is-invalid' ?>" placeholder="https://www.example.com">
                            <?= $inputValid ? '' : '<div class=invalid-feedback>Некорректный URL</div>' ?>
                        </div>
                        <div class="col-2">
                            <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
    <?php require '_footer.phtml' ?>
</body>

</html>