<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Анализатор страниц</title>
</head>
<body>
    <?php require '_header.phtml' ?>

    <main class="flex-grow-1">
        <div class="container-lg mt-3">
                      <h1>Упс что-то пошло не так</h1>
                    <div class="row row-cols-1 row-cols-lg-2 align-items-lg-center">
  <div class="col">
    <h2 class="h2 mb-4">
      Ошибка 500
    </h2>
  </div>
</div>
        </div>
    </main>



    </body>
</html>