<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Анализатор страниц</title>
</head>
<body>
<?php require '_header.phtml' ?>
    <div class="alert alert-<?=$flashType?>" role="alert">
           <?= htmlspecialchars($flash) ?>
      </div>
    <main class="flex-grow-1">
    <div class="container-lg mt-3">

    <row>
        <h1>Сайт <?=htmlspecialchars($site->getUrl())?></h1>
    </row>
      

  <div class="row">
      <div class="table-responsive">
        <table class="table table-bordered  table-hover text-nowrap" data-test="url">
          </thead>
          <tbody>
              <tr>
                 <td>ID</td>
                 <td><?=htmlspecialchars($site->getId())?></td>
              </tr>
              <tr>
                 <td>Имя</td>
                 <td><?=htmlspecialchars($site->getUrl()) ?></td>
                 </tr>
              <tr>
                 <td>Дата создания</td>
                 <td><?=htmlspecialchars($site->getTimestamp())?></td>
              </tr>
          </tbody>
        </table>
      </div>
   </div>




   <div class="row">
       <form method="post" action="/urls/<?=$site->getId()?>/checks">
           <input type="submit" class="btn btn-primary" value="Запустить проверку">
       </form>
       <div class="table-responsive mt-3">
       <table class="table table-bordered table-hover" data-test="checks">
           <thead>
               <tr>
                  <th>ID</th>
                  <th>Код ответа</th>
                  <th>h1</th>
                  <th>title</th>
                  <th>description</th>
                  <th>Дата создания</th>
               </tr>
            </thead>
            <tbody>
            <?php foreach($checks as $check): ?>
            
              <tr>
                 <td><?= htmlspecialchars($check->getId()) ?></td>
                 <td><?= htmlspecialchars($check->getStatusCode())?></td>
                 <td class="text-break"><?= htmlspecialchars($check->getH1())?></td>
                 <td class="text-break"><?= htmlspecialchars($check->getTitle())?></td>
                 <td class="text-break"><?= htmlspecialchars($check->getDescription())?></td>
                 <td class="text-break"><?= htmlspecialchars($check->getCreatedAt())?></td>
              </tr>
        
              
          <?php endforeach; ?>
           
          </tbody>
         </table>
       </div>
   </div>


  </div>
   

    </main>









    </body>
</html>