<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Анализатор страниц</title>
</head>
<body>
    <?= require '_header.phtml' ?>

    <?= $a ?>
    <div class="container mt-3">
  <h1>Сайты</h1>
  <div class="row">
      <div class="table-responsive">
        <table class="table table-bordered  table-hover text-nowrap">
          <thead>
            <tr>
              <th>ID</th>
              <th>Имя</th>
              <th>Последняя проверка</th>
              <th>Код ответа</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>www.github.com</td>
              <td>27.01.2025</td>
              <td>200</td>
            </tr>
            <tr>
            <td>2</td>
              <td>www.mail.ru</td>
              <td>17.01.2025</td>
              <td>300</td>
            </tr>
            <tr>
              <td>3</td>
              <td>www.deil.ru</td>
              <td>12.01.2025</td>
              <td>404</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
</div>
  










    </body>
</html>