<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Анализатор страниц</title>
</head>
<body>
    <?= require '_header.phtml' ?>

    <?= htmlspecialchars($flash) ?>
    <div class="container mt-3">
  <h1>Сайт</h1>
  <div class="row">
      <div class="table-responsive">
        <table class="table table-bordered  table-hover text-nowrap">
          <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Последняя проверка</th>
                <th>Код ответа</th>
            </tr>
          </thead>
          <tbody>
          <?php foreach($sites as $site): ?>
            
            <tr>
               <td class="text-break"><?= htmlspecialchars($site->getId()) ?></td>
               <td class="text-break"><?= htmlspecialchars($site->getUrl())?></td>
               <td class="text-break"><?= htmlspecialchars($site->getTimestamp())?></td>
            </tr>
      
            
        <?php endforeach; ?>



          </tbody>
        </table>

<table>

      </div>
    </div>
</div>
  










    </body>
</html>